globalThis.process ??= {}; globalThis.process.env ??= {};
import { e as createComponent, f as createAstro, h as addAttribute, k as renderHead, l as renderSlot, r as renderTemplate, n as renderComponent, o as renderScript, m as maybeRenderHead } from '../chunks/astro/server_BGdyjtYs.mjs';
/* empty css                                 */
export { renderers } from '../renderers.mjs';

const $$Astro = createAstro();
const $$Main = createComponent(($$result, $$props, $$slots) => {
  const Astro2 = $$result.createAstro($$Astro, $$props, $$slots);
  Astro2.self = $$Main;
  const { pageClass = "" } = Astro2.props;
  return renderTemplate`<html lang="en"${addAttribute(pageClass, "class")}> <head><meta charset="utf-8"><link rel="icon" type="image/png" href="https://i.imgur.com/wizwzbW.png"><!-- Force desktop version on mobile - zoom optimal pour remplir l'écran --><meta name="viewport" content="width=1200, initial-scale=0.32, minimum-scale=0.1, maximum-scale=2.0, user-scalable=yes"><meta name="generator"${addAttribute(Astro2.generator, "content")}><title>10 Sell</title>${renderHead()}</head> <!-- Dark mode class injection point - will be replaced with \`dark\` class based on your site palette --> <body class="__DARK_MODE_CLASS__"> ${renderSlot($$result, $$slots["default"])} </body></html>`;
}, "/app/src/layouts/main.astro", void 0);

const $$Index = createComponent(async ($$result, $$props, $$slots) => {
  const pageClass = "10-sell-page";
  return renderTemplate`${renderComponent($$result, "MainLayout", $$Main, { "pageClass": pageClass, "data-astro-cid-j7pv25f6": true }, { "default": async ($$result2) => renderTemplate`  ${maybeRenderHead()}<nav class="top-nav" data-astro-cid-j7pv25f6> <div class="nav-content" data-astro-cid-j7pv25f6> <div class="round-logo-container has-image" data-astro-cid-j7pv25f6> <img src="https://i.imgur.com/wizwzbW.png" alt="Logo" class="round-logo-image" style="display: block;" data-astro-cid-j7pv25f6> </div> <div class="nav-hero-container has-image" data-astro-cid-j7pv25f6> <img src="https://i.imgur.com/gfFI53u.png" alt="10 SELL Banner" class="nav-hero-image" style="display: block;" data-astro-cid-j7pv25f6> </div> </div> </nav> <div class="container" data-astro-cid-j7pv25f6> <!-- Header with Google Colors --> <header class="header" data-astro-cid-j7pv25f6> <div class="title-container" data-astro-cid-j7pv25f6> <h1 class="main-title" id="mainTitle" data-astro-cid-j7pv25f6> <span class="google-letter-1" data-astro-cid-j7pv25f6>M</span><span class="google-letter-2" data-astro-cid-j7pv25f6>y</span> <span class="google-letter-3" data-astro-cid-j7pv25f6>1</span><span class="google-letter-4" data-astro-cid-j7pv25f6>0</span> <span class="google-letter-5" data-astro-cid-j7pv25f6>S</span><span class="google-letter-6" data-astro-cid-j7pv25f6>E</span><span class="google-letter-1" data-astro-cid-j7pv25f6>L</span><span class="google-letter-2" data-astro-cid-j7pv25f6>L</span> <span class="google-letter-3" data-astro-cid-j7pv25f6>A</span><span class="google-letter-4" data-astro-cid-j7pv25f6>d</span><span class="google-letter-5" data-astro-cid-j7pv25f6>v</span><span class="google-letter-6" data-astro-cid-j7pv25f6>e</span><span class="google-letter-1" data-astro-cid-j7pv25f6>n</span><span class="google-letter-2" data-astro-cid-j7pv25f6>t</span><span class="google-letter-3" data-astro-cid-j7pv25f6>u</span><span class="google-letter-4" data-astro-cid-j7pv25f6>r</span><span class="google-letter-5" data-astro-cid-j7pv25f6>e</span> <span class="rocket" data-astro-cid-j7pv25f6>🚀</span> </h1> </div> <p id="subtitle" style="font-size: 24px; color: #5f6368; margin-top: 20px; font-weight: 400;" data-astro-cid-j7pv25f6>
The story of a crazy bet
</p> </header> <!-- Interactive Coin Section --> ${renderComponent($$result2, "CoinFlipSection", null, { "client:only": "react", "client:component-hydration": "only", "data-astro-cid-j7pv25f6": true, "client:component-path": "/app/src/components/CoinFlipSection", "client:component-export": "default" })} <!-- How it all started Section --> <section class="doc-section" data-astro-cid-j7pv25f6> <div class="doc-toggle" id="docToggle" data-astro-cid-j7pv25f6> <h3 data-astro-cid-j7pv25f6>💡 How it all started</h3> <span class="doc-arrow" id="docArrow" data-astro-cid-j7pv25f6>▼</span> </div> <div class="documentation" id="documentation" data-astro-cid-j7pv25f6> <p style="margin-bottom: 20px;" data-astro-cid-j7pv25f6>At first, I was completely intrigued by memecoins. I thought to myself that I too wanted to launch my own token.<br data-astro-cid-j7pv25f6>
I spent over a month asking myself this question: what token could I create that would be truly unique?</p> <p style="margin-bottom: 20px;" data-astro-cid-j7pv25f6>And then, since I'm passionate about casinos and love betting on things like blackjack or roulette, I thought:<br data-astro-cid-j7pv25f6>
why not create something around the coin flip game? Something simple but completely crazy. That's how the idea of 10 SELL was born.</p> <p style="margin-bottom: 0;" data-astro-cid-j7pv25f6>I wanted to make it unique, incredible, and above all transparent. So here's what I imagined...</p> </div> </section> <!-- How it really works Section --> <section class="info-section" data-astro-cid-j7pv25f6> <h2 style="font-size: 32px; color: #1a73e8; margin-bottom: 25px; font-weight: 500;" data-astro-cid-j7pv25f6>🎲 How it really works?</h2> <p class="info-text" data-astro-cid-j7pv25f6>So it's quite simple. I'm going to use Google's coin flip, <span class="mobile-break" data-astro-cid-j7pv25f6>you know the one everyone can use.<br data-astro-cid-j7pv25f6></span><span class="desktop-inline" data-astro-cid-j7pv25f6>you know the one everyone can use. </span>That way, no one can tell me I cheated or that I control the result.</p> <!-- IMAGE 1 - Google's coin flip --> <div class="image-upload-container has-image" data-astro-cid-j7pv25f6> <img src="https://i.imgur.com/VhDrVmd.png" alt="Google's coin flip" class="uploaded-image" style="display: block;" data-astro-cid-j7pv25f6> </div> <p class="info-text" style="margin-top: 30px;" data-astro-cid-j7pv25f6>
The principle: I flip the coin live. If it lands <strong data-astro-cid-j7pv25f6>10 times in a row on the same side</strong> <span class="mobile-break" data-astro-cid-j7pv25f6>(heads or tails),<br data-astro-cid-j7pv25f6></span><span class="desktop-inline" data-astro-cid-j7pv25f6>(heads or tails), </span><span class="highlight-sell" style="font-size: inherit;" data-astro-cid-j7pv25f6>I sell everything live in front of everyone</span>. There, it's as simple as that.
</p> <p class="info-text" data-astro-cid-j7pv25f6>
I even created a program on Google Sheets to track all this. With each flip, it counts: <span class="mobile-break" data-astro-cid-j7pv25f6>heads = 0, tails = 1.<br data-astro-cid-j7pv25f6></span><span class="desktop-inline" data-astro-cid-j7pv25f6>heads = 0, tails = 1. </span>And when we reach 10 of the same side, boom, it displays "SELL".
</p> <!-- IMAGE 2 - My Google Sheets program --> <div class="image-upload-container has-image" data-astro-cid-j7pv25f6> <img src="https://i.imgur.com/FTCg4ws.png" alt="My Google Sheets program" class="uploaded-image" style="display: block;" data-astro-cid-j7pv25f6> </div> </section> <!-- The live counter Section --> <section class="info-section" data-astro-cid-j7pv25f6> <h2 style="font-size: 32px; color: #1a73e8; margin-bottom: 25px; font-weight: 500;" data-astro-cid-j7pv25f6>⏱️ The live counter</h2> <p class="info-text" data-astro-cid-j7pv25f6>During the lives, I'll use a 1-hour counter. <span class="mobile-break" data-astro-cid-j7pv25f6><br data-astro-cid-j7pv25f6></span>When the counter stops, the live is over and we continue next time. That way it's clear for everyone.</p> <!-- IMAGE 3 - The Google counter --> <div class="image-upload-container has-image" data-astro-cid-j7pv25f6> <img src="https://i.imgur.com/BEI8LUO.png" alt="The Google counter" class="uploaded-image" style="display: block;" data-astro-cid-j7pv25f6> </div> </section> <!-- What it will look like Section --> <section class="info-section" data-astro-cid-j7pv25f6> <h2 style="font-size: 32px; color: #1a73e8; margin-bottom: 25px; font-weight: 500;" data-astro-cid-j7pv25f6>📱 What it will look like</h2> <p class="info-text" data-astro-cid-j7pv25f6>The lives will be done on X (Twitter) in mobile format because frankly, it's more pleasant to watch on phone.</p> <div style="background: #f8f9fa; padding: 25px; border-radius: 8px; margin: 25px 0;" data-astro-cid-j7pv25f6> <p class="info-text" style="margin-bottom: 12px;" data-astro-cid-j7pv25f6><strong data-astro-cid-j7pv25f6>At the top of the screen:</strong> Google's coin flip that I'll launch</p> <p class="info-text" style="margin-bottom: 12px;" data-astro-cid-j7pv25f6><strong data-astro-cid-j7pv25f6>In the center:</strong> the 1-hour counter that scrolls</p> <p class="info-text" data-astro-cid-j7pv25f6><strong data-astro-cid-j7pv25f6>At the bottom:</strong> my Google Sheets program with buttons that go up and down to count</p> </div> <!-- VIDEO 4 - Preview of the mobile live format --> <div class="image-upload-container has-image video-container" style="max-width: 900px; background: transparent;" data-astro-cid-j7pv25f6> <div id="videoWrapper" style="width: 100%; height: 100%; position: relative; background: #000;" data-astro-cid-j7pv25f6> <video id="mainVideo" controls controlslist="nodownload noremoteplayback" disablepictureinpicture style="width: 100%; height: 100%; object-fit: contain; border-radius: 8px;" lang="en" data-astro-cid-j7pv25f6> <source src="https://i.imgur.com/TOA0mm0.mp4" type="video/mp4" data-astro-cid-j7pv25f6>
Your browser does not support the video tag.
</video> <!-- Custom Fullscreen Button --> <button id="customFullscreenBtn" title="Fullscreen" style="position: absolute; top: 15px; right: 15px; background: rgba(0, 0, 0, 0.7); border: none; border-radius: 6px; padding: 10px; cursor: pointer; z-index: 10; transition: all 0.2s ease; display: flex; align-items: center; justify-content: center;" data-astro-cid-j7pv25f6> <svg id="fullscreenIcon" width="24" height="24" viewBox="0 0 24 24" fill="white" data-astro-cid-j7pv25f6> <path d="M7 14H5v5h5v-2H7v-3zm-2-4h2V7h3V5H5v5zm12 7h-3v2h5v-5h-2v3zM14 5v2h3v3h2V5h-5z" data-astro-cid-j7pv25f6></path> </svg> <svg id="exitFullscreenIcon" width="24" height="24" viewBox="0 0 24 24" fill="white" style="display: none;" data-astro-cid-j7pv25f6> <path d="M5 16h3v3h2v-5H5v2zm3-8H5v2h5V5H8v3zm6 11h2v-3h3v-2h-5v5zm2-11V5h-2v5h5V8h-3z" data-astro-cid-j7pv25f6></path> </svg> </button> </div> </div> </section> <!-- Why join now Section --> <section class="info-section why-join-section" data-astro-cid-j7pv25f6> <h2 class="why-join-title" style="font-size: 32px; color: #1a73e8; margin-bottom: 25px; font-weight: 500; text-align: center;" data-astro-cid-j7pv25f6>💎 Why join now?</h2> <p class="info-text text-center-all compact-mobile" style="text-align: center;" data-astro-cid-j7pv25f6>Honestly, I think this is a completely crazy concept. Nobody knows when the coin will land 10 times in a row on the same side.</p> <p class="info-text text-center-all compact-mobile" style="text-align: center;" data-astro-cid-j7pv25f6>It could be in 5 minutes or in 1 hour. <span style="color: #ea4335; font-weight: 600;" data-astro-cid-j7pv25f6>That's what makes it exciting.</span></p> <p class="info-text text-center-all compact-mobile" style="text-align: center;" data-astro-cid-j7pv25f6>And above all, everything is transparent. I use tools that everyone knows: Google's coin flip, Google Sheets, a simple counter. <strong style="color: #ea4335;" data-astro-cid-j7pv25f6>Zero manipulation possible.</strong></p> <p class="info-text text-center-all compact-mobile" style="text-align: center;" data-astro-cid-j7pv25f6>And even if at the end of the hour I haven't reached 10, it's not over. On the contrary, it's an opportunity to buy even more as the token continues its progression.</p> <p class="info-text text-center-all compact-mobile" style="text-align: center;" data-astro-cid-j7pv25f6>The most thrilling moment? When I reach <strong style="color: #ea4335;" data-astro-cid-j7pv25f6>9 out of 10</strong>. If I break the streak, there will inevitably be people who panic and sell.</p> <p class="info-text text-center-all compact-mobile" style="text-align: center;" data-astro-cid-j7pv25f6>And there, <strong style="color: #34a853;" data-astro-cid-j7pv25f6>boom, it's the perfect opportunity to buy at the lowest.</strong></p> <p class="info-text" style="font-size: 20px; font-weight: 600; text-align: center; margin: 30px 0;" data-astro-cid-j7pv25f6>
That's why it's important to watch my lives: <strong style="color: #4285f4;" data-astro-cid-j7pv25f6>you'll know exactly when to buy and when to sell.</strong> </p> <div style="background: white; border: 2px solid #34a853; border-radius: 12px; padding: 30px; margin: 35px auto; max-width: 800px; box-shadow: 0 2px 8px rgba(0,0,0,0.1);" data-astro-cid-j7pv25f6> <h3 style="font-size: 28px; margin-bottom: 20px; font-weight: 700; color: #34a853; text-align: center;" data-astro-cid-j7pv25f6>💎 No locked liquidity</h3> <p style="font-size: 20px; line-height: 1.7; color: #3c4043; text-align: center;" data-astro-cid-j7pv25f6>
My concept requires it: if I land 10 times in a row, I must sell everything live during the stream. That's why I can't lock the liquidity. 
Instead: <strong style="color: #ea4335;" data-astro-cid-j7pv25f6>100% public wallet</strong> (check on DexScreener). Total transparency.
</p> </div> </section> <!-- When are the lives Section --> <section class="info-section" data-astro-cid-j7pv25f6> <h2 style="font-size: 36px; margin-bottom: 30px; font-weight: 500; color: #1a73e8;" data-astro-cid-j7pv25f6>⏰ When are the lives?</h2> <div style="background: white; border: 2px solid #4285f4; border-radius: 12px; padding: 30px; margin-bottom: 35px; box-shadow: 0 2px 8px rgba(0,0,0,0.1);" data-astro-cid-j7pv25f6> <h3 style="font-size: 28px; margin-bottom: 20px; font-weight: 700; color: #ea4335;" data-astro-cid-j7pv25f6>🔥 WHENEVER I FEEL LIKE IT</h3> <p style="font-size: 20px; margin-bottom: 25px; line-height: 1.6; color: #3c4043;" data-astro-cid-j7pv25f6>I do the lives when I feel like it, without fixed schedule. It can be:</p> <div style="display: flex; gap: 25px; justify-content: center; flex-wrap: wrap; margin-bottom: 20px;" data-astro-cid-j7pv25f6> <div style="font-size: 18px; font-weight: 600; color: #4285f4;" data-astro-cid-j7pv25f6>🌅 Morning</div> <div style="font-size: 18px; font-weight: 600; color: #34a853;" data-astro-cid-j7pv25f6>☀️ Afternoon</div> <div style="font-size: 18px; font-weight: 600; color: #fbbc05;" data-astro-cid-j7pv25f6>🌙 Evening</div> </div> <p style="font-size: 18px; color: #5f6368; font-style: italic;" data-astro-cid-j7pv25f6>This unpredictability is what makes it even crazier.</p> </div> <div style="background: white; border: 2px solid #fbbc05; border-radius: 12px; padding: 30px; margin-bottom: 35px; box-shadow: 0 2px 8px rgba(0,0,0,0.1);" data-astro-cid-j7pv25f6> <h3 style="font-size: 28px; margin-bottom: 20px; font-weight: 700; color: #ea4335;" data-astro-cid-j7pv25f6>⚡ ONLY 10-15 MINUTES WARNING</h3> <p style="font-size: 20px; line-height: 1.7; color: #3c4043;" data-astro-cid-j7pv25f6>
I only warn <strong data-astro-cid-j7pv25f6>10-15 minutes before on X</strong>. <span class="mobile-break" data-astro-cid-j7pv25f6><br data-astro-cid-j7pv25f6></span>If you miss the alert, you potentially miss <strong style="color: #ea4335;" data-astro-cid-j7pv25f6>THE historic moment</strong> when I'm going to sell everything.
</p> </div> <div style="background: white; border: 2px solid #34a853; border-radius: 12px; padding: 30px; margin-bottom: 35px; box-shadow: 0 2px 8px rgba(0,0,0,0.1);" data-astro-cid-j7pv25f6> <h3 style="font-size: 28px; margin-bottom: 20px; font-weight: 700; color: #34a853;" data-astro-cid-j7pv25f6>⏱️ 1 HOUR MAXIMUM</h3> <p style="font-size: 20px; line-height: 1.7; color: #3c4043;" data-astro-cid-j7pv25f6>
Each live lasts <strong data-astro-cid-j7pv25f6>1 hour maximum</strong>. <span class="mobile-break" data-astro-cid-j7pv25f6><br data-astro-cid-j7pv25f6></span>During this hour, we flip the coin, we count, and if we reach 10, <span style="color: #ea4335; font-weight: 700;" data-astro-cid-j7pv25f6>I sell live in front of everyone</span>.
</p> </div> <div style="margin-top: 40px; text-align: center;" data-astro-cid-j7pv25f6> <a href="https://x.com/10SellOfficial" target="_blank" rel="noopener noreferrer" class="google-button pulse-button" style="background: #4285f4; color: white; font-size: 22px; padding: 25px 60px; margin-top: 20px; border: none; box-shadow: 0 6px 20px rgba(66, 133, 244, 0.3); text-decoration: none; display: inline-block;" data-astro-cid-j7pv25f6>
🔔 ENABLE NOTIFICATIONS ON X
</a> <p style="font-size: 18px; margin-top: 25px; color: #3c4043; font-weight: 600; background: #fce8e6; padding: 20px; border-radius: 8px; max-width: 700px; margin-left: auto; margin-right: auto; border: 1px solid #ea4335;" data-astro-cid-j7pv25f6>
⚠️ Without notifications enabled, you WILL MISS the live.
</p> </div> </section> <!-- An Honest Project Section --> <section class="info-section" data-astro-cid-j7pv25f6> <h2 style="font-size: 36px; margin-bottom: 30px; font-weight: 500; color: #1a73e8; text-align: center;" data-astro-cid-j7pv25f6>⚖️ An Honest Project, A Clear Commitment</h2> <div style="background: white; border: 2px solid #fbbc05; border-radius: 12px; padding: 35px; margin: 35px auto; max-width: 900px; box-shadow: 0 2px 8px rgba(0,0,0,0.1);" data-astro-cid-j7pv25f6> <p style="font-size: 22px; line-height: 1.7; color: #3c4043; text-align: center; margin-bottom: 15px;" data-astro-cid-j7pv25f6>
I won't lie to you: if after <strong style="color: #ea4335;" data-astro-cid-j7pv25f6>3 months</strong> the project doesn't take off<br data-astro-cid-j7pv25f6>
(less than <strong style="color: #ea4335;" data-astro-cid-j7pv25f6>500 followers on X</strong>), I'll stop properly.
</p> <p style="font-size: 20px; line-height: 1.7; color: #3c4043; text-align: center; margin-bottom: 25px; margin-top: 25px;" data-astro-cid-j7pv25f6>
If I have to stop, you'll be warned <strong style="color: #4285f4;" data-astro-cid-j7pv25f6>7 days before</strong>. Last live, we say goodbye with respect.
</p> <div style="background: #f8f9fa; padding: 25px; border-radius: 8px; margin: 30px 0;" data-astro-cid-j7pv25f6> <p style="font-size: 20px; font-weight: 600; color: #ea4335; text-align: center; margin-bottom: 12px;" data-astro-cid-j7pv25f6>
No ghosting. No surprises.
</p> </div> <p style="font-size: 22px; line-height: 1.7; color: #3c4043; text-align: center; margin-bottom: 20px;" data-astro-cid-j7pv25f6>
But if it works? We build something crazy together. <span style="font-size: 28px;" data-astro-cid-j7pv25f6>🚀</span> </p> </div> </section> <!-- Coming Soon Section --> <section class="info-section" style="text-align: center;" data-astro-cid-j7pv25f6> <h2 style="font-size: 40px; margin-bottom: 25px; font-weight: 500; color: #1a73e8;" data-astro-cid-j7pv25f6>🚀 COMING SOON</h2> <div style="padding: 35px; max-width: 900px; margin: 35px auto;" data-astro-cid-j7pv25f6> <p style="font-size: 22px; font-weight: 400; line-height: 1.7; margin-bottom: 25px; color: #202124;" data-astro-cid-j7pv25f6>
I always have ideas running through my head and I like to share them with you.<br data-astro-cid-j7pv25f6>
The more the project grows, the more I'll be able to implement crazy stuff.
</p> <p style="font-size: 16px; color: #5f6368; margin-top: 20px;" data-astro-cid-j7pv25f6>
Stay connected on X, I'm going to announce some stuff soon.
</p> </div> </section> <!-- Token Address Section --> ${renderComponent($$result2, "TokenSection", null, { "client:only": "react", "client:component-hydration": "only", "data-astro-cid-j7pv25f6": true, "client:component-path": "/app/src/components/TokenSection", "client:component-export": "default" })} </div>  <footer class="footer" data-astro-cid-j7pv25f6> <h3 style="font-size: 28px; color: #202124; margin-bottom: 30px; font-weight: 500;" data-astro-cid-j7pv25f6>🌐 Join us on X</h3> <div style="display: flex; gap: 25px; justify-content: center; flex-wrap: wrap; margin-bottom: 35px;" data-astro-cid-j7pv25f6> <a href="https://x.com/10SellOfficial" target="_blank" rel="noopener noreferrer" style="display: inline-flex; align-items: center; gap: 12px; padding: 15px 30px; background: #1a73e8; color: white; text-decoration: none; border-radius: 8px; font-weight: 500; transition: all 0.2s ease; font-size: 18px;" data-astro-cid-j7pv25f6> <svg style="width: 24px; height: 24px;" fill="currentColor" viewBox="0 0 24 24" data-astro-cid-j7pv25f6> <path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z" data-astro-cid-j7pv25f6></path> </svg>
Follow us on X
</a> </div> <p style="color: #5f6368; font-size: 18px; max-width: 700px; margin: 0 auto; line-height: 1.6;" data-astro-cid-j7pv25f6>
💎 A transparent and completely crazy adventure, one flip at a time.
</p> <p style="color: #dadce0; font-size: 16px; margin-top: 35px; padding-top: 25px; border-top: 1px solid #e8eaed;" data-astro-cid-j7pv25f6>
© 2025 10 SELL Token • All rights reserved
</p> </footer> ` })}  ${renderScript($$result, "/app/src/pages/index.astro?astro&type=script&index=0&lang.ts")}`;
}, "/app/src/pages/index.astro", void 0);

const $$file = "/app/src/pages/index.astro";
const $$url = "";

const _page = /*#__PURE__*/Object.freeze(/*#__PURE__*/Object.defineProperty({
	__proto__: null,
	default: $$Index,
	file: $$file,
	url: $$url
}, Symbol.toStringTag, { value: 'Module' }));

const page = () => _page;

export { page };
